language: rust
rust:
  - stable
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
deploy:
  provider: cargo
  token: "cargo publish KrspNh2OlTzKFZGCJUy2qPCDjtDI8GKI"
  file:  target/*
  on:
    tags: true

