language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
deploy:
  provider: cargo
  token: "cargo login KrspNh2OlTzKFZGCJUy2qPCDjtDI8GKI"
